site:
  title: My Documentation Site
  start_page: component-name::index.adoc
content:
  sources:
    - url: https://github.com/kimball80/Asciidoc_Antora.git
      branches: [main]
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true